//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoloAdventureToolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoloAdventureToolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawful Good
        ///Lawful Good
        ///Lawful Good
        ///Lawful Good
        ///Lawful Good
        ///Lawful Good
        ///Neutral Good
        ///Chaotic Good
        ///Lawful neutral
        ///True Neutral
        ///True Neutral
        ///True Neutral
        ///True Neutral
        ///True Neutral
        ///Chaotic Neutral
        ///Lawful Evil
        ///Lawful Evil
        ///Lawful Evil
        ///Lawful Evil
        ///Neutral Evil
        ///Neutral Evil
        ///Neutral Evil
        ///Neutral Evil
        ///Chaotic Evil.
        /// </summary>
        public static string Alignment {
            get {
                return ResourceManager.GetString("Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shy
        ///Aloof / Superior
        ///Foolsih / idiotic
        ///Cocky / arrogant
        ///Envious
        ///Grumpy
        ///Mischievous (good or evil)
        ///Playful / joking
        ///Insane
        ///Abrubt / Unpredictavle
        ///Melancholics/ Airy
        ///Romantic
        ///Frustrated
        ///Stressed
        ///Weird
        ///Serene / peaceful
        ///Cagy / mysterious
        ///Distracted
        ///Sad
        ///Single-Minded
        ///Angry
        ///Blase
        ///Joyous
        ///Venegful
        ///Malicious
        ///Afraid
        ///Disgusted
        ///Resignation
        ///Nostalgic
        ///Envious
        ///Determined
        ///Pity
        ///Disdain
        ///Hopelessness
        ///Amused
        ///Reckless
        ///Lonley
        ///Frivolous
        ///Disoriented.
        /// </summary>
        public static string Disposition {
            get {
                return ResourceManager.GetString("Disposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destitute / Homeless
        ///Poor
        ///Poor
        ///Just getting by
        ///Just getting by
        ///Can support themselves
        ///Can support themselves
        ///Climbing the ladder
        ///Climbing the ladder
        ///Comfortable
        ///Comfortable
        ///Comfortable
        ///Comfortable
        ///Well-off
        ///Well-off
        ///Well-off
        ///Rich
        ///Rich
        ///Extremely weathly
        ///Extremely weathly
        ///Royalty-level weathly.
        /// </summary>
        public static string EconomicStatus {
            get {
                return ResourceManager.GetString("EconomicStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EpicQuest {
            get {
                object obj = ResourceManager.GetObject("EpicQuest", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketch
        ///Achemedes
        ///Elle
        ///Zip
        ///Dhist
        ///Kolt
        ///Kat
        ///Mert
        ///Lefgorey
        ///Mers
        ///Ploltts
        ///Tik
        ///Stellan
        ///Wendy
        ///Orlaith
        ///Wilf
        ///Foon
        ///Ephron
        ///Steemo
        ///Gisele
        ///Aario
        ///Bixala
        ///Dobre
        ///Ellianra
        ///Icthar
        ///Noen
        ///Phrex
        ///Osk
        ///Ja&apos;ak
        ///Ret
        ///Dresp
        ///Nlaps
        ///Qwency
        ///Surly
        ///Friis
        ///Plist
        ///Bodeen
        ///Welsh
        ///Ernst
        ///Tiali
        ///Yorm
        ///Ulb
        ///Proots
        ///Neb
        ///Prex
        ///Prag
        ///Oceferous
        ///Smeff
        ///Gerts
        ///Tiludo
        ///Viavaror
        ///Ceptobus
        ///Kopeck
        ///Jency
        ///Mima
        ///Rea
        ///Tovek
        ///Pik
        ///Blim
        ///Gratooni
        ///Thule
        ///Sperry
        ///Wef
        ///Lift
        ///Gurt
        ///Golah
        ///Flint
        ///Jurd
        ///Hubert
        ///Tersec
        ///Lars
        ///Wex
        ///Octane
        ///Ergas
        ///Stirge
        ///Shmorgen
        ///Basil
        ///Shank
        ///Sprink
        ///Davich
        ///Klurv
        ///Chumtrol
        ///Chenc [rest of string was truncated]&quot;;.
        /// </summary>
        public static string first_names
        {
            get {
                return ResourceManager.GetString("first_names", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dreyton
        ///Jim
        ///Nifco
        ///Dewcoln
        ///Frison
        ///Gormely
        ///Grips
        ///Greeg
        ///Smitts
        ///Starshorn
        ///Gurnel
        ///Towooka
        ///Cubano
        ///Drolkton
        ///Judge
        ///Spratt
        ///Theloon
        ///Tunso
        ///Hecht
        ///Mendregar
        ///Turandi
        ///Brost
        ///Vere
        ///Fisk
        ///Fong
        ///Durst
        ///Bort
        ///Clenpith
        ///Ulion
        ///Kabbel
        ///Dovrin
        ///Frent
        ///Vilx
        ///Holotid
        ///Gurmsen
        ///Yamsen
        ///Riblets
        ///Illpton
        ///Golv
        ///Surett
        ///Avernus
        ///Shimson
        ///Ilkjibbs
        ///Hampton
        ///Otag
        ///Sblimp
        ///Satsens
        ///Bilterm
        ///Sprog
        ///Eem
        ///Lim
        ///Cassells
        ///Sabaldo
        ///Kadem
        ///Yoru
        ///Thrimp
        ///Afsoon
        ///Cegno
        ///Apantar
        ///Voktop
        ///Frol
        ///Anod
        ///Sion
        ///Sterngazer
        ///Trucdo
        ///Domroy
        ///Cirro
        ///Steely
        ///Rigardi
        ///Havewood
        ///Ignal
        ///Topo
        ///Hutch
        ///Heckengard
        ///M [rest of string was truncated]&quot;;.
        /// </summary>
        public static string last_names {
            get {
                return ResourceManager.GetString("last_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmer
        ///Artist
        ///Herbalist
        ///Horse trainer
        ///Blacksmith
        ///Finesmith
        ///Blacksmith
        ///Jeweller
        ///Entertainer
        ///Teacher
        ///Armourer
        ///Cook
        ///Tailor
        ///Ropemaker
        ///Fletcher
        ///Miller
        ///Executioner
        ///Restauranteur
        ///Priest/Cultist
        ///Enginerr
        ///Scribe
        ///Soldier
        ///Banker
        ///Apothecary
        ///Woodcutter
        ///Tax Colelctor
        ///Prostitute
        ///Fishmonger
        ///Butcher
        ///Fruiterer.
        /// </summary>
        public static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unjust killing
        ///Crime committed, criminal disappeared
        ///Item lost
        ///Tyrant(s) threaten town / business / population (monster / humanoid)
        ///Environmental disturbance / Strange Weather / Infestation / Plague
        ///Magical chaos / Curse
        ///Kidnapping / Hostage situation
        ///Adventurer left some time ago, but is lost
        ///Something is rumoured, but undiscovered (Artefact, legendary place)
        ///Riches rumoured within secure, guarded place
        ///Invasion
        ///Person suspected of something
        ///Important item / message / person needs transporting        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Quest_Problems {
            get {
                return ResourceManager.GetString("Quest_Problems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice board
        ///A dream
        ///NPC
        ///Local temple gives you the quest
        ///Tavern rumour
        ///Rumour picked up at guard station
        ///Stumble into situation
        ///Merchant’s Guild / merchants
        ///Guild affiliate
        ///Noble family entrusts you
        ///Fellow adventurer
        ///Event sparks a memory
        ///Mysterious scroll with info on it 
        ///Divine inspiration
        ///Hidden piece of paper inside a basic reward / purchase a pc makes
        ///Overheard conversation
        ///Treasure map 
        ///Passing traveller
        ///Found journal - Owner missing
        ///Entrusted with delivering a parcel. Something co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string QuestSource {
            get {
                return ResourceManager.GetString("QuestSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaracokra
        ///Aasimar
        ///Bugbear
        ///Centaur
        ///Changeling
        ///Deep Gnome
        ///Dhampir
        ///Dragonborn
        ///Duergar
        ///Hill Dwarf
        ///Mountain Dwarf
        ///Eladrin
        ///Drow
        ///Wood Elf
        ///High Elf
        ///Fariy
        ///Firbolg
        ///Fire Genasi
        ///Air Genasi
        ///Water Genasi
        ///Earth Genasi
        ///Githyanki
        ///Githzerai
        ///Rock Gnome
        ///Forest Gnome
        ///Deep Gnome
        ///Goblin
        ///Half Elf
        ///Half Orc
        ///Halfling
        ///Ling
        ///Harengon
        ///Hexblood
        ///Hobgoblin
        ///Human
        ///Kalashtar
        ///Kenku
        ///Kobold
        ///Leonin
        ///Lizardfolk
        ///Loxodon
        ///Minotaur
        ///Orc
        ///Owlin
        ///Reborn
        ///Satyr
        ///Sea Elf
        ///Shadar-Kai
        ///Shifter
        ///Simic Hybrid
        ///Tabaxi
        ///Ti [rest of string was truncated]&quot;;.
        /// </summary>
        public static string races {
            get {
                return ResourceManager.GetString("races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenge
        ///Apprehend / Bounty Hunt
        ///Retrieval
        ///Repel / Sabotage / Deceive / Sabotage / Extort / Entrap
        ///Investigate / Solve
        ///Investigate / Lift curse / Destroy magic
        ///Rescue / Recover
        ///Rescue
        ///Explore / Discover
        ///Loot
        ///Repel / Divert
        ///Spy / Gather information
        ///Transport / smuggle / escort
        ///Waylay / Hijack
        ///Find / Destroy
        ///Investigate / Implicate / Incriminate / Expose
        ///Transport supplies
        ///Research / Explore / Decode
        ///Survive
        ///Protect, eliminate threat
        ///Prevent
        ///Break
        ///Negotiate / Prepare / Mediate / Participa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ResultantQuest {
            get {
                return ResourceManager.GetString("ResultantQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abandon
        ///abolish
        ///abuse
        ///accuse
        ///address
        ///aggravate
        ///agitate
        ///aid
        ///aim
        ///alarm
        ///alert
        ///alter
        ///amaze
        ///ambush
        ///amuse
        ///annihilate
        ///annoy
        ///antagonize
        ///appeal
        ///applaud
        ///apprehend
        ///approach
        ///argue
        ///arise
        ///arouse
        ///arrange
        ///arrest
        ///ask
        ///assassinate
        ///assault
        ///assemble
        ///astonish
        ///attack
        ///attempt
        ///attend
        ///auction
        ///audition
        ///avenge
        ///avert
        ///babble
        ///badmouth
        ///bait
        ///ban
        ///banish
        ///baptize
        ///bargain
        ///bark
        ///barricade
        ///barter
        ///bash
        ///bawl
        ///beautify
        ///beckon
        ///befriend
        ///beg
        ///beguile
        ///belch
        ///belittle
        ///bellow
        ///bemoan
        ///bequeath
        ///berate [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Verbs {
            get {
                return ResourceManager.GetString("Verbs", resourceCulture);
            }
        }
    }
}
